// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../src/app/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessment/input/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment/input">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessment/input/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audit/session-snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/session-snapshot">> = Specific
  const handler = {} as typeof import("../../src/app/api/audit/session-snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clinical-language/assess-input/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clinical-language/assess-input">> = Specific
  const handler = {} as typeof import("../../src/app/api/clinical-language/assess-input/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clinical-language/respond/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clinical-language/respond">> = Specific
  const handler = {} as typeof import("../../src/app/api/clinical-language/respond/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dialogue-agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dialogue-agent">> = Specific
  const handler = {} as typeof import("../../src/app/api/dialogue-agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/homework/store/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/homework/store">> = Specific
  const handler = {} as typeof import("../../src/app/api/homework/store/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/participants/store/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/participants/store">> = Specific
  const handler = {} as typeof import("../../src/app/api/participants/store/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/patient-reflection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/patient-reflection">> = Specific
  const handler = {} as typeof import("../../src/app/api/patient-reflection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/protocol-studio/store/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/protocol-studio/store">> = Specific
  const handler = {} as typeof import("../../src/app/api/protocol-studio/store/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/runtime/session-store/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runtime/session-store">> = Specific
  const handler = {} as typeof import("../../src/app/api/runtime/session-store/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/safety/store/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/safety/store">> = Specific
  const handler = {} as typeof import("../../src/app/api/safety/store/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/speech/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/speech/transcribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/speech/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/worksheets/store/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/worksheets/store">> = Specific
  const handler = {} as typeof import("../../src/app/api/worksheets/store/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
