import { sourceText } from "@/lib/protocol/source-fidelity-catalog";
import type { SessionSourceMetadata, SessionSpec } from "@/lib/protocol/source-fidelity-catalog";

const metadata: SessionSourceMetadata = {
  number: 3,
  id: "tbct-s03",
  title: "Intrapersonal Thought Record (Intra-TR)",
  techniqueName: "Intrapersonal Thought Record (Intra-TR)",
  acronym: "Intra-TR",
  sourceLineStart: 430,
  sourceLineEnd: 745,
  sourceSessionHash: "2a3686ef5660f60d28fa1a59783e03a3d29763faaf223ad9e0a08e50d5644745",
  contextRange: [471, 482],
  roleRange: [441, 454],
  languageRange: [441, 454],
  openingRange: [455, 470],
  requiredActionsRange: [483, 698],
  restrictionsRange: [699, 724],
  safetyRange: [455, 470],
};

export const spec: SessionSpec = {
  metadata,
  nodes: [
    {
      slug: "safety-check",
      title: "Safety Protocol",
      type: "session_start",
      source: [455, 470],
      requiredFields: ["safetyCheck"],
      safetyRuleIds: ["TBCT-S03-CRISIS-PAUSE"],
      restrictions: [sourceText([455, 470])],
      nextSlug: "intra-tr-introduction",
      prompts: [
        { slug: "safety-check", type: "opening", source: [455, 470], marker: "Before we start, how are you doing today", outputFields: ["safetyCheck"], validation: { kind: "safety_check" }, completionEffect: { type: "evaluate_safety" }, safetyRuleIds: ["TBCT-S03-CRISIS-PAUSE"] },
      ],
    },
    {
      slug: "intra-tr-introduction",
      title: "Introducing the Intra-TR",
      type: "orientation",
      source: [483, 494],
      requiredFields: ["intraTrIntroductionComplete"],
      restrictions: [sourceText([483, 494])],
      prompts: [
        { slug: "fourteen-question-introduction", type: "opening", source: [483, 494], marker: "Today we are going to work with something called", outputFields: ["intraTrIntroductionComplete"] },
        { slug: "ccd-connection", type: "explanation", source: [483, 494], marker: "You may remember the diagram", outputFields: ["intraTrIntroductionComplete"] },
      ],
    },
    {
      slug: "q1-situation",
      title: "Q1 - Situation",
      type: "question",
      source: [501, 510],
      requiredFields: ["situation"],
      prompts: [
        { slug: "describe-situation", type: "question", source: [501, 510], marker: "Can you describe a recent situation", outputFields: ["situation"], validation: { kind: "text" } },
        { slug: "specific-moment", type: "clarification", source: [501, 510], marker: "Can you give me a specific moment", activationCondition: { field: "situationIsAbstract", operator: "equals", value: true }, outputFields: ["situation"] },
      ],
    },
    {
      slug: "q2-automatic-thought",
      title: "Q2a - Automatic Thought",
      type: "question",
      source: [511, 528],
      requiredFields: ["automaticThought"],
      nextSlug: "q2b-at-belief",
      prompts: [
        { slug: "automatic-thought", type: "question", source: [511, 528], marker: "At that exact moment", outputFields: ["automaticThought"], validation: { kind: "text" } },
        { slug: "emotion-to-thought-redirect", type: "clarification", source: [511, 528], marker: "When you feel overwhelmed", activationCondition: { field: "automaticThoughtReportedAsFeeling", operator: "equals", value: true }, outputFields: ["automaticThought"] },
      ],
    },
    {
      slug: "factual-thought-meaning",
      title: "Q2a - Factual Automatic Thought Follow-up",
      type: "condition",
      source: [511, 528],
      requiredFields: ["workingAutomaticThought", "factualThoughtConfirmed"],
      nextSlug: "q2b-at-belief",
      restrictions: [sourceText([511, 528])],
      prompts: [
        { slug: "factual-thought-meaning", type: "follow_up", source: [511, 528], marker: "I can see that is true", outputFields: ["workingAutomaticThought"] },
        { slug: "confirm-working-thought", type: "confirmation", source: [511, 528], marker: "So the thought we'll be working with", outputFields: ["factualThoughtConfirmed"], validation: { kind: "boolean" } },
      ],
    },
    {
      slug: "q2b-at-belief",
      title: "Q2b - Belief in the Automatic Thought",
      type: "assessment",
      source: [529, 536],
      requiredFields: ["automaticThoughtBeliefPercent"],
      prompts: [
        { slug: "rate-at-belief", type: "rating", source: [529, 536], marker: "How much do you believe that thought", outputFields: ["automaticThoughtBeliefPercent"], validation: { kind: "rating", min: 0, max: 100 } },
      ],
    },
    {
      slug: "q3-emotion",
      title: "Q3 - Emotion and Intensity",
      type: "assessment",
      source: [537, 550],
      requiredFields: ["primaryEmotion", "primaryEmotionIntensityPercent"],
      prompts: [
        { slug: "primary-emotion", type: "question", source: [537, 550], marker: "When you have that thought", outputFields: ["primaryEmotion"] },
        { slug: "strongest-emotion", type: "clarification", source: [537, 550], marker: "Which one feels strongest", activationCondition: { field: "multipleEmotionsReported", operator: "equals", value: true }, outputFields: ["primaryEmotion"] },
        { slug: "emotion-intensity", type: "rating", source: [537, 550], marker: "How strong is that emotion", outputFields: ["primaryEmotionIntensityPercent"], validation: { kind: "rating", min: 0, max: 100 } },
      ],
    },
    {
      slug: "q4-behavior-body-summary",
      title: "Q4 - Behavior, Body, and Participant Summary",
      type: "assessment",
      source: [551, 572],
      requiredFields: ["behavior", "bodySensations", "participantSummary"],
      prompts: [
        { slug: "behavior", type: "question", source: [551, 572], marker: "What do you do when you have that thought", outputFields: ["behavior"] },
        { slug: "body-sensations", type: "question", source: [551, 572], marker: "And what do you notice in your body", outputFields: ["bodySensations"] },
        { slug: "participant-summary", type: "summary", source: [551, 572], marker: "Before we continue, could you summarize", outputFields: ["participantSummary"], validation: { kind: "participant_summary_required" } },
        { slug: "cycle-note", type: "reflection", source: [551, 572], marker: "You can see how this pattern", outputFields: ["cycleSummaryAcknowledged"] },
      ],
    },
    {
      slug: "q5-q7-behavior-and-distortion",
      title: "Q5-Q7 - Behavior Pros, Cons, and Cognitive Distortion",
      type: "question",
      source: [573, 596],
      requiredFields: ["behaviorPros", "behaviorCons", "cognitiveDistortion"],
      prompts: [
        { slug: "behavior-pros", type: "question", source: [573, 596], marker: "Are there any advantages or benefits", outputFields: ["behaviorPros"] },
        { slug: "behavior-pros-follow-up", type: "follow_up", source: [573, 596], marker: "We tend to do things for a reason", activationCondition: { field: "behaviorProsDenied", operator: "equals", value: true }, outputFields: ["behaviorPros"] },
        { slug: "behavior-cons", type: "question", source: [573, 596], marker: "And what are the disadvantages", outputFields: ["behaviorCons"] },
        { slug: "cognitive-distortion", type: "question", source: [573, 596], marker: "Looking at your automatic thought", outputFields: ["cognitiveDistortion"] },
      ],
    },
    {
      slug: "q8-q9-evidence",
      title: "Q8-Q9 - Evidence Examination",
      type: "question",
      source: [597, 616],
      requiredFields: ["evidenceFor", "evidenceAgainst"],
      restrictions: [sourceText([597, 616])],
      prompts: [
        { slug: "evidence-for", type: "question", source: [597, 616], marker: "Is there any evidence that supports", outputFields: ["evidenceFor"], validation: { kind: "array", minItems: 2, maxItems: 3, promptOnceIfSingle: true } },
        { slug: "evidence-for-more", type: "follow_up", source: [597, 616], marker: "Can you think of one or two more", activationCondition: { field: "evidenceForCount", operator: "less_than", value: 2 }, outputFields: ["evidenceFor"] },
        { slug: "evidence-against", type: "question", source: [597, 616], marker: "Now, on the other side", outputFields: ["evidenceAgainst"], validation: { kind: "array", minItems: 2, maxItems: 3, promptOnceIfSingle: true } },
        { slug: "evidence-against-direction", type: "follow_up", source: [597, 616], marker: "Think about recent days or weeks", activationCondition: { field: "evidenceAgainstCount", operator: "less_than", value: 2 }, outputFields: ["evidenceAgainst"] },
      ],
    },
    {
      slug: "q10-conclusion",
      title: "Q10 - Balanced Conclusion",
      type: "question",
      source: [617, 634],
      requiredFields: ["balancedConclusion", "conclusionTherefore", "conclusionBeliefPercent"],
      restrictions: [sourceText([617, 634])],
      prompts: [
        { slug: "balanced-conclusion", type: "question", source: [617, 634], marker: "Taking all of this evidence together", outputFields: ["balancedConclusion"] },
        { slug: "therefore-extension", type: "follow_up", source: [617, 634], marker: "Can you take that further", outputFields: ["conclusionTherefore"] },
        { slug: "full-conclusion-readback", type: "confirmation", source: [617, 634], marker: "So your conclusion is", outputFields: ["conclusionReadBackComplete"] },
        { slug: "conclusion-belief", type: "rating", source: [617, 634], marker: "How much do you believe that entire conclusion", outputFields: ["conclusionBeliefPercent"], validation: { kind: "rating", min: 0, max: 100, requiresField: "conclusionReadBackComplete" } },
      ],
    },
    {
      slug: "q11-new-emotions",
      title: "Q11 - New Emotions",
      type: "assessment",
      source: [635, 658],
      requiredFields: ["positiveEmotions", "originalEmotionRerating", "newEmotionIntensities"],
      restrictions: [sourceText([635, 658])],
      prompts: [
        { slug: "positive-emotions-first", type: "question", source: [635, 658], marker: "Now that you have reached this conclusion", outputFields: ["positiveEmotions"] },
        { slug: "original-negative-emotion", type: "question", source: [635, 658], marker: "And what about [emotion named at Q3a]", outputFields: ["originalEmotionRerating"], validation: { kind: "same_field_reference", field: "primaryEmotion" } },
        { slug: "emotion-intensities", type: "rating", source: [635, 658], outputFields: ["newEmotionIntensities"], validation: { kind: "rating", min: 0, max: 100, allowedEmotionSources: ["positiveEmotions", "primaryEmotion"] } },
      ],
    },
    {
      slug: "q12-q14-final-evaluation",
      title: "Q12-Q14 - Intended Action and Final Evaluation",
      type: "assessment",
      source: [659, 686],
      requiredFields: ["intendedActions", "newBodySensations", "revisedAutomaticThoughtBeliefPercent", "globalEvaluation"],
      prompts: [
        { slug: "intended-action", type: "question", source: [659, 686], marker: "What do you intend to do now", outputFields: ["intendedActions"] },
        { slug: "action-plan-bridge", type: "transition", source: [659, 686], marker: "Those sound like the beginning", activationCondition: { field: "intendedActions", operator: "exists" } },
        { slug: "new-body-sensations", type: "question", source: [659, 686], marker: "What do you notice in your body now", outputFields: ["newBodySensations"] },
        { slug: "repeat-exact-at", type: "rating", source: [659, 686], marker: "How much do you now believe the original automatic thought", outputFields: ["revisedAutomaticThoughtBeliefPercent"], validation: { kind: "rating", min: 0, max: 100, repeatExactField: "automaticThought" } },
        { slug: "global-evaluation", type: "question", source: [659, 686], marker: "And overall, how are you now", outputFields: ["globalEvaluation"], validation: { kind: "enum", values: ["same", "a little better", "much better"] } },
      ],
    },
    {
      slug: "closing",
      title: "Closing the Session",
      type: "session_complete",
      source: [687, 698],
      restrictions: [sourceText([699, 724])],
      terminal: true,
      prompts: [
        { slug: "closing-review", type: "closing", source: [687, 698], marker: "You did important work today", outputFields: ["closingReview"] },
        { slug: "action-plan-offer", type: "transition", source: [687, 698], marker: "If you'd like, we can also", outputFields: ["actionPlanOffer"], completionEffect: { type: "complete_session" } },
      ],
    },
    {
      slug: "safety-pause",
      title: "Safety Pause and Escalation",
      type: "clinician_escalation",
      source: [455, 470],
      safetyRuleIds: ["TBCT-S03-CRISIS-PAUSE"],
      terminal: true,
      prompts: [
        { slug: "pause-and-escalate", type: "instruction", source: [455, 470], outputFields: ["safetyEscalation"], completionEffect: { type: "pause_session" }, safetyRuleIds: ["TBCT-S03-CRISIS-PAUSE"] },
      ],
    },
  ],
  extraEdges: [
    { sourceSlug: "safety-check", targetSlug: "safety-pause", edgeType: "safety", source: [455, 470], label: "Crisis signal", condition: { field: "crisisSignal", operator: "equals", value: true }, priority: 1 },
    { sourceSlug: "q2-automatic-thought", targetSlug: "factual-thought-meaning", edgeType: "conditional", source: [511, 528], label: "Factual thought", condition: { field: "automaticThoughtIsFactual", operator: "equals", value: true }, priority: 1 },
  ],
};
