"use client";

import dynamic from "next/dynamic";
import { usePathname } from "next/navigation";

const DashboardPage = dynamic(() => import("@/components/pages/dashboard-page").then((mod) => mod.DashboardPage), { ssr: false });
const AssetsPage = dynamic(() => import("@/components/pages/assets-page").then((mod) => mod.AssetsPage), { ssr: false });
const ClinicalAssetRegistrationPage = dynamic(() => import("@/components/pages/clinical-asset-registration-page").then((mod) => mod.ClinicalAssetRegistrationPage), { ssr: false });
const ExtractionPage = dynamic(() => import("@/components/pages/extraction-page").then((mod) => mod.ExtractionPage), { ssr: false });
import { ProtocolPage } from "@/components/pages/protocol-page";
const SafetyPage = dynamic(() => import("@/components/pages/safety-page").then((mod) => mod.SafetyPage), { ssr: false });
const ValidationPage = dynamic(() => import("@/components/pages/validation-page").then((mod) => mod.ValidationPage), { ssr: false });
const VersionsPage = dynamic(() => import("@/components/pages/versions-page").then((mod) => mod.VersionsPage), { ssr: false });
const AuditPage = dynamic(() => import("@/components/pages/audit-page").then((mod) => mod.AuditPage), { ssr: false });
const SettingsPage = dynamic(() => import("@/components/pages/settings-page").then((mod) => mod.SettingsPage), { ssr: false });
const PatientListPage = dynamic(() => import("@/components/pages/patient-list-page").then((mod) => mod.PatientListPage), { ssr: false });
const PatientNewSessionPage = dynamic(() => import("@/components/pages/patient-new-session-page").then((mod) => mod.PatientNewSessionPage), { ssr: false });
const PatientSessionPage = dynamic(() => import("@/components/pages/patient-session-page").then((mod) => mod.PatientSessionPage), { ssr: false });
const PatientSessionCompletePage = dynamic(() => import("@/components/pages/patient-session-complete-page").then((mod) => mod.PatientSessionCompletePage), { ssr: false });
const PatientProfilePage = dynamic(() => import("@/components/pages/patient-profile-page").then((mod) => mod.PatientProfilePage), { ssr: false });
const PatientMemoryPage = dynamic(() => import("@/components/pages/patient-memory-page").then((mod) => mod.PatientMemoryPage), { ssr: false });
const RuntimeInspectorPage = dynamic(() => import("@/components/pages/runtime-inspector-page").then((mod) => mod.RuntimeInspectorPage), { ssr: false });
const RuntimeEscalationsPage = dynamic(() => import("@/components/pages/runtime-escalations-page").then((mod) => mod.RuntimeEscalationsPage), { ssr: false });
const RuntimeParticipantPage = dynamic(() => import("@/components/pages/runtime-participant-page").then((mod) => mod.RuntimeParticipantPage), { ssr: false });
const RuntimeMemoryReviewPage = dynamic(() => import("@/components/pages/runtime-memory-review-page").then((mod) => mod.RuntimeMemoryReviewPage), { ssr: false });
const RuntimeSessionSummaryPage = dynamic(() => import("@/components/pages/runtime-session-summary-page").then((mod) => mod.RuntimeSessionSummaryPage), { ssr: false });
const RuntimeSafetyDashboardPage = dynamic(() => import("@/components/pages/runtime-safety-dashboard-page").then((mod) => mod.RuntimeSafetyDashboardPage), { ssr: false });
const RuntimeSafetyEventsPage = dynamic(() => import("@/components/pages/runtime-safety-events-page").then((mod) => mod.RuntimeSafetyEventsPage), { ssr: false });
const RuntimeSafetyEventDetailPage = dynamic(() => import("@/components/pages/runtime-safety-event-detail-page").then((mod) => mod.RuntimeSafetyEventDetailPage), { ssr: false });
const RuntimeSafetyMyQueuePage = dynamic(() => import("@/components/pages/runtime-safety-my-queue-page").then((mod) => mod.RuntimeSafetyMyQueuePage), { ssr: false });
const RuntimeSafetyFollowUpsPage = dynamic(() => import("@/components/pages/runtime-safety-followups-page").then((mod) => mod.RuntimeSafetyFollowUpsPage), { ssr: false });
const RuntimeSafetyNotificationsPage = dynamic(() => import("@/components/pages/runtime-safety-notifications-page").then((mod) => mod.RuntimeSafetyNotificationsPage), { ssr: false });
const RuntimeSafetyAnalyticsPage = dynamic(() => import("@/components/pages/runtime-safety-analytics-page").then((mod) => mod.RuntimeSafetyAnalyticsPage), { ssr: false });
const RuntimeSafetyReportDetailPage = dynamic(() => import("@/components/pages/runtime-safety-report-detail-page").then((mod) => mod.RuntimeSafetyReportDetailPage), { ssr: false });
const RuntimePilotDashboardPage = dynamic(() => import("@/components/pages/runtime-pilot-dashboard-page").then((mod) => mod.RuntimePilotDashboardPage), { ssr: false });
const RuntimePilotConfigurationPage = dynamic(() => import("@/components/pages/runtime-pilot-configuration-page").then((mod) => mod.RuntimePilotConfigurationPage), { ssr: false });
const RuntimePilotSitesPage = dynamic(() => import("@/components/pages/runtime-pilot-sites-page").then((mod) => mod.RuntimePilotSitesPage), { ssr: false });
const RuntimePilotParticipantsPage = dynamic(() => import("@/components/pages/runtime-pilot-participants-page").then((mod) => mod.RuntimePilotParticipantsPage), { ssr: false });
const RuntimePilotParticipantDetailPage = dynamic(() => import("@/components/pages/runtime-pilot-participant-detail-page").then((mod) => mod.RuntimePilotParticipantDetailPage), { ssr: false });
const RuntimePilotScreeningPage = dynamic(() => import("@/components/pages/runtime-pilot-screening-page").then((mod) => mod.RuntimePilotScreeningPage), { ssr: false });
const RuntimePilotEnrollmentPage = dynamic(() => import("@/components/pages/runtime-pilot-enrollment-page").then((mod) => mod.RuntimePilotEnrollmentPage), { ssr: false });
const RuntimePilotAllocationPage = dynamic(() => import("@/components/pages/runtime-pilot-allocation-page").then((mod) => mod.RuntimePilotAllocationPage), { ssr: false });
const RuntimePilotSessionsPage = dynamic(() => import("@/components/pages/runtime-pilot-sessions-page").then((mod) => mod.RuntimePilotSessionsPage), { ssr: false });
const RuntimePilotDeviationsPage = dynamic(() => import("@/components/pages/runtime-pilot-deviations-page").then((mod) => mod.RuntimePilotDeviationsPage), { ssr: false });
const RuntimePilotOutcomesPage = dynamic(() => import("@/components/pages/runtime-pilot-outcomes-page").then((mod) => mod.RuntimePilotOutcomesPage), { ssr: false });
const RuntimePilotDataQualityPage = dynamic(() => import("@/components/pages/runtime-pilot-data-quality-page").then((mod) => mod.RuntimePilotDataQualityPage), { ssr: false });
const RuntimePilotExportsPage = dynamic(() => import("@/components/pages/runtime-pilot-exports-page").then((mod) => mod.RuntimePilotExportsPage), { ssr: false });
const RuntimePilotReportsPage = dynamic(() => import("@/components/pages/runtime-pilot-reports-page").then((mod) => mod.RuntimePilotReportsPage), { ssr: false });
const RuntimePilotReportDetailPage = dynamic(() => import("@/components/pages/runtime-pilot-report-detail-page").then((mod) => mod.RuntimePilotReportDetailPage), { ssr: false });

export function StudioApp() {
  const path = usePathname();
  if (path.includes("/patient/profile")) return <PatientProfilePage />;
  if (path.includes("/patient/memory")) return <PatientMemoryPage />;
  if (path.includes("/patient/sessions/new")) return <PatientNewSessionPage />;
  if (path.includes("/patient/sessions/") && path.endsWith("/complete")) return <PatientSessionCompletePage />;
  if (path.includes("/patient/sessions/")) return <PatientSessionPage />;
  if (path.includes("/patient")) return <PatientListPage />;
  if (path.includes("/runtime/pilot/participants/")) return <RuntimePilotParticipantDetailPage />;
  if (path.includes("/runtime/pilot/reports/")) return <RuntimePilotReportDetailPage />;
  if (path.includes("/runtime/pilot/configuration")) return <RuntimePilotConfigurationPage />;
  if (path.includes("/runtime/pilot/sites")) return <RuntimePilotSitesPage />;
  if (path.includes("/runtime/pilot/participants")) return <RuntimePilotParticipantsPage />;
  if (path.includes("/runtime/pilot/screening")) return <RuntimePilotScreeningPage />;
  if (path.includes("/runtime/pilot/enrollment")) return <RuntimePilotEnrollmentPage />;
  if (path.includes("/runtime/pilot/allocation")) return <RuntimePilotAllocationPage />;
  if (path.includes("/runtime/pilot/sessions")) return <RuntimePilotSessionsPage />;
  if (path.includes("/runtime/pilot/deviations")) return <RuntimePilotDeviationsPage />;
  if (path.includes("/runtime/pilot/outcomes")) return <RuntimePilotOutcomesPage />;
  if (path.includes("/runtime/pilot/data-quality")) return <RuntimePilotDataQualityPage />;
  if (path.includes("/runtime/pilot/exports")) return <RuntimePilotExportsPage />;
  if (path.includes("/runtime/pilot/reports")) return <RuntimePilotReportsPage />;
  if (path.includes("/runtime/pilot")) return <RuntimePilotDashboardPage />;
  if (path.includes("/runtime/safety/events/")) return <RuntimeSafetyEventDetailPage />;
  if (path.includes("/runtime/safety/reports/")) return <RuntimeSafetyReportDetailPage />;
  if (path.includes("/runtime/safety/events")) return <RuntimeSafetyEventsPage />;
  if (path.includes("/runtime/safety/my-queue")) return <RuntimeSafetyMyQueuePage />;
  if (path.includes("/runtime/safety/follow-ups")) return <RuntimeSafetyFollowUpsPage />;
  if (path.includes("/runtime/safety/notifications")) return <RuntimeSafetyNotificationsPage />;
  if (path.includes("/runtime/safety/analytics")) return <RuntimeSafetyAnalyticsPage />;
  if (path.includes("/runtime/safety")) return <RuntimeSafetyDashboardPage />;
  if (path.includes("/runtime/memory-review")) return <RuntimeMemoryReviewPage />;
  if (path.includes("/runtime/participants/")) return <RuntimeParticipantPage />;
  if (path.includes("/runtime/sessions/") && path.endsWith("/summary")) return <RuntimeSessionSummaryPage />;
  if (path.includes("/runtime/escalations")) return <RuntimeEscalationsPage />;
  if (path.includes("/runtime/sessions/")) return <RuntimeInspectorPage />;
  if (path.includes("/clinical-assets/new")) return <ClinicalAssetRegistrationPage />;
  if (path.includes("/assets")) return <AssetsPage/>;
  if (path.includes("/extraction")) return <ExtractionPage/>;
  if (path.includes("/canvas")) return <ProtocolPage/>;
  if (path.includes("/safety")) return <SafetyPage/>;
  if (path.includes("/validation")) return <ValidationPage/>;
  if (path.includes("/versions") || path.includes("/release")) return <VersionsPage/>;
  if (path.startsWith("/audit")) return <AuditPage/>;
  if (path.startsWith("/settings")) return <SettingsPage/>;
  return <DashboardPage/>;
}
