import type { WorksheetBinding } from "@/types/worksheet";

// Session 4 (Interpersonal Thought Record / Inter-TR, Fig. A7) worksheet
// binding registry. Mirrors the figure's two halves -- "Me" (situation
// through behavior/body) and "Other person" (their likely thought, emotion,
// behavior) -- plus the final check and Action Plan fields.
export const TBCT_S04_BINDINGS: WorksheetBinding[] = [
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "interpersonalSituation", worksheetFieldKey: "interpersonalSituation", visualElementId: "box-situation", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Situation", labelKo: "상황", sourceSection: "Q1", displayOrder: 0 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "patientAutomaticThought", worksheetFieldKey: "patientAutomaticThought", visualElementId: "box-my-thought", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "My automatic thought", labelKo: "내 자동적 사고", sourceSection: "Q2a", displayOrder: 1 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "patientAutomaticThoughtBeliefPercent", worksheetFieldKey: "patientAutomaticThoughtBeliefPercent", visualElementId: "gauge-my-belief", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Belief in my thought", labelKo: "내 생각에 대한 믿음 정도", sourceSection: "Q2b", displayOrder: 2 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "patientEmotion", worksheetFieldKey: "patientEmotion", visualElementId: "box-my-emotion", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "My emotion", labelKo: "내 감정", sourceSection: "Q3a", displayOrder: 3 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "patientEmotionIntensityPercent", worksheetFieldKey: "patientEmotionIntensityPercent", visualElementId: "gauge-my-emotion", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "My emotion intensity", labelKo: "내 감정 강도", sourceSection: "Q3b", displayOrder: 4 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "patientBehavior", worksheetFieldKey: "patientBehavior", visualElementId: "box-my-behavior", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "My behavior", labelKo: "내 행동", sourceSection: "Q4a", displayOrder: 5 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "patientBodySensations", worksheetFieldKey: "patientBodySensations", visualElementId: "box-my-body", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "What I notice in my body", labelKo: "내 몸에서 느껴지는 것", sourceSection: "Q4b", displayOrder: 6 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "otherPersonLikelyThought", worksheetFieldKey: "otherPersonLikelyThought", visualElementId: "box-other-thought", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Their likely thought", labelKo: "상대방이 했을 생각", sourceSection: "Q5", displayOrder: 7 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "otherPersonLikelyEmotion", worksheetFieldKey: "otherPersonLikelyEmotion", visualElementId: "box-other-emotion", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Their likely emotion", labelKo: "상대방이 느꼈을 감정", sourceSection: "Q6", displayOrder: 8 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "otherPersonLikelyBehavior", worksheetFieldKey: "otherPersonLikelyBehavior", visualElementId: "box-other-behavior", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Their likely behavior", labelKo: "상대방이 했을 행동", sourceSection: "Q7", displayOrder: 9 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "locusOfControlRecognition", worksheetFieldKey: "locusOfControlRecognition", visualElementId: "box-leverage", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "The part I can change", labelKo: "내가 바꿀 수 있는 부분", sourceSection: "Part 4", displayOrder: 10 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "revisedPatientAutomaticThoughtBeliefPercent", worksheetFieldKey: "revisedPatientAutomaticThoughtBeliefPercent", visualElementId: "gauge-revised-belief", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Belief now (Q8)", labelKo: "지금의 믿음 정도", sourceSection: "Q8", displayOrder: 11 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "finalEvaluation", worksheetFieldKey: "finalEvaluation", visualElementId: "chip-final-evaluation", valueType: "choice", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "How I'm feeling now (Q9)", labelKo: "지금의 느낌", sourceSection: "Q9", displayOrder: 12 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "plannedActions", worksheetFieldKey: "plannedActions", visualElementId: "list-actions", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Proposed actions", labelKo: "제안된 행동", sourceSection: "Action Plan", displayOrder: 13 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "actionObstacles", worksheetFieldKey: "actionObstacles", visualElementId: "list-obstacles", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Possible obstacles", labelKo: "예상되는 장애물", sourceSection: "Action Plan", displayOrder: 14 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "obstacleSolutions", worksheetFieldKey: "obstacleSolutions", visualElementId: "list-solutions", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Solutions", labelKo: "해결 방법", sourceSection: "Action Plan", displayOrder: 15 },
  { sessionDefinitionId: "tbct-s04", canonicalFieldKey: "implementationTiming", worksheetFieldKey: "implementationTiming", visualElementId: "list-timing", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "When", labelKo: "언제", sourceSection: "Action Plan", displayOrder: 16 },
];
