import type { WorksheetBinding } from "@/types/worksheet";

// Session 8 (Trial One / TBTR) worksheet binding registry. The source
// trial has many sequential belief/emotion checkpoints (defendant's chair,
// revisited after every stage) -- the composed worksheet condenses these
// into a single before/after trajectory rather than one box per checkpoint,
// alongside the actual case content (charge, evidence, verdict, appeal).
export const TBCT_S08_BINDINGS: WorksheetBinding[] = [
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "charge", worksheetFieldKey: "charge", visualElementId: "box-charge", valueType: "long_text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "The charge", sourceSection: "Step 3", displayOrder: 0 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "coreBeliefBaselinePercent", worksheetFieldKey: "coreBeliefBaselinePercent", visualElementId: "gauge-belief-start", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Belief at the start", sourceSection: "Step 2", displayOrder: 1 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "prosecutionEvidence", worksheetFieldKey: "prosecutionEvidence", visualElementId: "list-prosecution", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Prosecutor's plea", sourceSection: "Step 6", displayOrder: 2 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "defendantPostProsecutionBeliefPercent", worksheetFieldKey: "defendantPostProsecutionBeliefPercent", visualElementId: "gauge-belief-post-prosecution", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Belief after the prosecution", sourceSection: "Step 6", displayOrder: 3 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "defenseEvidence", worksheetFieldKey: "defenseEvidence", visualElementId: "list-defense", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Defense attorney's plea", sourceSection: "Step 8", displayOrder: 4 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "defendantPostDefenseBeliefPercent", worksheetFieldKey: "defendantPostDefenseBeliefPercent", visualElementId: "gauge-belief-post-defense", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Belief after the defense", sourceSection: "Step 9", displayOrder: 5 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "prosecutionRebuttals", worksheetFieldKey: "prosecutionRebuttals", visualElementId: "list-rebuttal", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Prosecutor's rebuttal (\"but...\")", sourceSection: "Step 10", displayOrder: 6 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "thereforeConclusions", worksheetFieldKey: "thereforeConclusions", visualElementId: "list-therefore", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Defense's reply (\"...therefore\")", sourceSection: "Step 12", displayOrder: 7 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "defendantPostRebuttalBeliefPercent", worksheetFieldKey: "defendantPostRebuttalBeliefPercent", visualElementId: "gauge-belief-post-rebuttal", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Belief after the rebuttal/reply", sourceSection: "Step 13", displayOrder: 8 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "verdict", worksheetFieldKey: "verdict", visualElementId: "chip-verdict", valueType: "choice", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "The jury's verdict", sourceSection: "Step 14", displayOrder: 9 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "defendantPostVerdictBeliefPercent", worksheetFieldKey: "defendantPostVerdictBeliefPercent", visualElementId: "gauge-belief-post-verdict", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Belief after the verdict", sourceSection: "Step 16", displayOrder: 10 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "positiveBelief", worksheetFieldKey: "positiveBelief", visualElementId: "box-positive-belief", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "My new positive belief", sourceSection: "Step 18", displayOrder: 11 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "positiveBeliefPercent", worksheetFieldKey: "positiveBeliefPercent", visualElementId: "gauge-positive-belief", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Belief in the new belief", sourceSection: "Step 20", displayOrder: 12 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "appealEvidence", worksheetFieldKey: "appealEvidence", visualElementId: "list-appeal", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Appeal evidence", sourceSection: "Step 19", displayOrder: 13 },
  { sessionDefinitionId: "tbct-s08", canonicalFieldKey: "originalChargeFinalBeliefPercent", worksheetFieldKey: "originalChargeFinalBeliefPercent", visualElementId: "gauge-belief-final", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Belief in the original charge (final)", sourceSection: "Step 21", displayOrder: 14 },
];
