import type { WorksheetBinding } from "@/types/worksheet";

// Session 1 (Introduction to the TBCT Model / CCD Level 1) worksheet
// binding registry -- backs the composed s01-worksheet.tsx (the "recreate
// the figure in real components" approach, not a photo overlay). Every
// canonicalFieldKey here is a real PromptItem.outputFields[0] value from
// source-fidelity-catalog.ts's tbct-s01 spec. Covers the three-candidate
// teaching cycle (which has clean discrete fields) and the participant's
// own reflection fields; the personal cycle itself only has "link
// recognition" fields in the source (no discrete personal
// situation/thought/emotion/behavior quad), so the composed worksheet
// grounds the live cycle diagram in the candidate example and reflects the
// personal insights as a separate summary section.
export const TBCT_S01_BINDINGS: WorksheetBinding[] = [
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "situationThoughtDistinction", worksheetFieldKey: "situationThoughtDistinction", visualElementId: "box-situation", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "My situation", sourceSection: "Step 1", displayOrder: 0 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "candidateOneEmotion", worksheetFieldKey: "candidateOneEmotion", visualElementId: "box-c1-emotion", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Candidate 1 · Emotion", sourceSection: "Step 2", displayOrder: 1 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "candidateOneThought", worksheetFieldKey: "candidateOneThought", visualElementId: "box-c1-thought", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Candidate 1 · Thought", sourceSection: "Step 2", displayOrder: 2 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "candidateOneBehavior", worksheetFieldKey: "candidateOneBehavior", visualElementId: "box-c1-behavior", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Candidate 1 · Behavior", sourceSection: "Step 2", displayOrder: 3 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "candidateTwoEmotion", worksheetFieldKey: "candidateTwoEmotion", visualElementId: "box-c2-emotion", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Candidate 2 · Emotion", sourceSection: "Step 2", displayOrder: 4 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "candidateTwoThought", worksheetFieldKey: "candidateTwoThought", visualElementId: "box-c2-thought", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Candidate 2 · Thought", sourceSection: "Step 2", displayOrder: 5 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "candidateTwoBehavior", worksheetFieldKey: "candidateTwoBehavior", visualElementId: "box-c2-behavior", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Candidate 2 · Behavior", sourceSection: "Step 2", displayOrder: 6 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "candidateThreeEmotion", worksheetFieldKey: "candidateThreeEmotion", visualElementId: "box-c3-emotion", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Candidate 3 · Emotion", sourceSection: "Step 2", displayOrder: 7 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "candidateThreeThought", worksheetFieldKey: "candidateThreeThought", visualElementId: "box-c3-thought", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Candidate 3 · Thought", sourceSection: "Step 2", displayOrder: 8 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "candidateThreeBehavior", worksheetFieldKey: "candidateThreeBehavior", visualElementId: "box-c3-behavior", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Candidate 3 · Behavior", sourceSection: "Step 2", displayOrder: 9 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "threePersonModelInsight", worksheetFieldKey: "threePersonModelInsight", visualElementId: "box-insight", valueType: "long_text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "What the three-person example showed me", sourceSection: "Step 2", displayOrder: 10 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "personalThoughtEmotionLink", worksheetFieldKey: "personalThoughtEmotionLink", visualElementId: "box-personal-1", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Thought → Emotion, in my own cycle", sourceSection: "Step 3", displayOrder: 11 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "personalEmotionBehaviorLink", worksheetFieldKey: "personalEmotionBehaviorLink", visualElementId: "box-personal-2", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Emotion → Behavior, in my own cycle", sourceSection: "Step 3", displayOrder: 12 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "personalBehaviorSituationLink", worksheetFieldKey: "personalBehaviorSituationLink", visualElementId: "box-personal-3", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Behavior → Situation (the loop back)", sourceSection: "Step 3", displayOrder: 13 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "participantSummary", worksheetFieldKey: "participantSummary", visualElementId: "box-summary", valueType: "long_text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: true, displayMode: "confirmed_summary", label: "My summary", sourceSection: "Step 4", displayOrder: 14 },
  { sessionDefinitionId: "tbct-s01", canonicalFieldKey: "participantSelectedDistortions", worksheetFieldKey: "participantSelectedDistortions", visualElementId: "chip-distortions", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Distortions I recognized", sourceSection: "Step 5", displayOrder: 15 },
];
