import type { WorksheetBinding } from "@/types/worksheet";

// Session 7 (Consensual Role-Play, CRP) worksheet binding registry --
// mirrors the CRP form: decisional balance (disadvantages/advantages),
// Emotion/Reason weights, empty-chair dialogue, consensus, decision, and
// the Action Plan.
export const TBCT_S07_BINDINGS: WorksheetBinding[] = [
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "desiredOrFearedAction", worksheetFieldKey: "desiredOrFearedAction", visualElementId: "box-decision", valueType: "text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Desired / feared action", sourceSection: "Step 1", displayOrder: 0 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "disadvantages", worksheetFieldKey: "disadvantages", visualElementId: "list-disadvantages", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Disadvantages", sourceSection: "Step 1", displayOrder: 1 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "advantages", worksheetFieldKey: "advantages", visualElementId: "list-advantages", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Advantages", sourceSection: "Step 1", displayOrder: 2 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "emotionDisadvantageWeight", worksheetFieldKey: "emotionDisadvantageWeight", visualElementId: "gauge-emotion-weight", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Emotion's weight (disadvantages)", sourceSection: "Step 2", displayOrder: 3 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "reasonAdvantageWeight", worksheetFieldKey: "reasonAdvantageWeight", visualElementId: "gauge-reason-weight", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Reason's weight (advantages)", sourceSection: "Step 2", displayOrder: 4 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "emotionReasonDialogue", worksheetFieldKey: "emotionReasonDialogue", visualElementId: "list-dialogue", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Emotion ↔ Reason", sourceSection: "Step 3", displayOrder: 5 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "consensusLearning", worksheetFieldKey: "consensusLearning", visualElementId: "box-consensus", valueType: "long_text", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "From the Consensus chair", sourceSection: "Step 4", displayOrder: 6 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "consensusAdvantageWeight", worksheetFieldKey: "consensusAdvantageWeight", visualElementId: "gauge-consensus-adv", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Consensus · Advantages", sourceSection: "Step 5", displayOrder: 7 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "consensusDisadvantageWeight", worksheetFieldKey: "consensusDisadvantageWeight", visualElementId: "gauge-consensus-dis", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Consensus · Disadvantages", sourceSection: "Step 5", displayOrder: 8 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "implementationReadiness", worksheetFieldKey: "implementationReadiness", visualElementId: "chip-readiness", valueType: "choice", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "verbatim", label: "Decision", sourceSection: "Step 6", displayOrder: 9 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "proposedActions", worksheetFieldKey: "proposedActions", visualElementId: "list-actions", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Proposed actions", sourceSection: "Step 7", displayOrder: 10 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "possibleObstacles", worksheetFieldKey: "possibleObstacles", visualElementId: "list-obstacles", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Possible obstacles", sourceSection: "Step 7", displayOrder: 11 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "obstacleSolutions", worksheetFieldKey: "obstacleSolutions", visualElementId: "list-solutions", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Solutions", sourceSection: "Step 7", displayOrder: 12 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "implementationPlan", worksheetFieldKey: "implementationPlan", visualElementId: "list-when", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "When and how", sourceSection: "Step 7", displayOrder: 13 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "supportPeople", worksheetFieldKey: "supportPeople", visualElementId: "list-support", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Who can support me", sourceSection: "Step 7", displayOrder: 14 },
  { sessionDefinitionId: "tbct-s07", canonicalFieldKey: "followUpPlan", worksheetFieldKey: "followUpPlan", visualElementId: "list-followup", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Follow-up", sourceSection: "Step 7", displayOrder: 15 },
];
