import type { WorksheetBinding } from "@/types/worksheet";

// Session 5 (Participation Grid) worksheet binding registry. contributors
// is an array (participant listed last per source); participationRatingsRound1
// is the parallel first-round array; participationRatingRounds accumulates
// rounds 2-5. guilt/shame are separate baseline->final tracks (cognitive
// belief vs. emotional intensity registers, per the source's own distinction).
export const TBCT_S05_BINDINGS: WorksheetBinding[] = [
  { sessionDefinitionId: "tbct-s05", canonicalFieldKey: "contributors", worksheetFieldKey: "contributors", visualElementId: "list-contributors", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Contributors", labelKo: "기여자 목록", sourceSection: "Step 3", displayOrder: 0 },
  { sessionDefinitionId: "tbct-s05", canonicalFieldKey: "participationRatingsRound1", worksheetFieldKey: "participationRatingsRound1", visualElementId: "chip-round1", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "Round 1 (%)", labelKo: "1라운드 (%)", sourceSection: "Step 4", displayOrder: 1 },
  { sessionDefinitionId: "tbct-s05", canonicalFieldKey: "participantParticipationRound1", worksheetFieldKey: "participantParticipationRound1", visualElementId: "chip-self-round1", valueType: "percentage", participantOwned: false, assistantMustNotSupply: false, confirmationRequired: false, displayMode: "number", label: "My own share, Round 1", labelKo: "1라운드 내 몫", sourceSection: "Step 4", displayOrder: 2 },
  { sessionDefinitionId: "tbct-s05", canonicalFieldKey: "guiltBeliefBaseline", worksheetFieldKey: "guiltBeliefBaseline", visualElementId: "gauge-guilt-start", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Guilt belief (start)", labelKo: "죄책감 믿음 (시작 시점)", sourceSection: "Step 1", displayOrder: 3 },
  { sessionDefinitionId: "tbct-s05", canonicalFieldKey: "guiltBeliefFinal", worksheetFieldKey: "guiltBeliefFinal", visualElementId: "gauge-guilt-end", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Guilt belief (now)", labelKo: "죄책감 믿음 (지금)", sourceSection: "Step 7", displayOrder: 4 },
  { sessionDefinitionId: "tbct-s05", canonicalFieldKey: "shameIntensityBaseline", worksheetFieldKey: "shameIntensityBaseline", visualElementId: "gauge-shame-start", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Shame intensity (start)", labelKo: "수치심 강도 (시작 시점)", sourceSection: "Step 1", displayOrder: 5 },
  { sessionDefinitionId: "tbct-s05", canonicalFieldKey: "shameIntensityFinal", worksheetFieldKey: "shameIntensityFinal", visualElementId: "gauge-shame-end", valueType: "percentage", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "number", label: "Shame intensity (now)", labelKo: "수치심 강도 (지금)", sourceSection: "Step 7", displayOrder: 6 },
  { sessionDefinitionId: "tbct-s05", canonicalFieldKey: "valuesArticulated", worksheetFieldKey: "valuesArticulated", visualElementId: "chip-values", valueType: "text_list", participantOwned: true, assistantMustNotSupply: true, confirmationRequired: false, displayMode: "list", label: "What matters to me", labelKo: "나에게 중요한 것", sourceSection: "Step 8", displayOrder: 7 },
];
